[package]
name = "lobster-sandbox-setup"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
clap.workspace = true
lobster-sandbox-installation = { path = "../lobster-sandbox-installation" }
serde_json.workspace = true

[lints]
workspace = true
